### ISSUE TITLE
Wifi and Zigbee network issue

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#109]
Yesterday early morning I noticed my a lot of devices (ESP boards + 2.5G devices) were offline. Some but not all devices. After rebooting my Unifi APs things connected again. Before I rebooted my APs I restarted Home Assistant and deCONZ.

Later in the day, my lights stopped working. Possibly linked to restarting/updating deCONZ. I tried various things to recover the Zigbee lights, deCONZ was connecting to the Conbee II stick but then dropping it after a period of time. I decided to remove the USB stick from my machine, add it again, and then restart deCONZ. This seemed to do the trick, however, Home Assistant was still not playing nicely with the lights. I was getting errors when calling services. In the end, I removed the deCONZ integration and restore it. The lights and sensors worked just fine then.

Due to removing the integration, I lost changes I made to entities and their mapping to an area. This isn't a fun task with over 150 Zigbee devices. Renames include appending light and tamper sensors with ```_lux```, ```_tamper``` and changing temperature sensors ```_humidity``` and ```_pressure``` as these are not named clearly. I then add ```_lightgroup``` to the deCONZ light groups that get synced over.

**Comment by CCOSTAN** [comment]
I guess this is one of the problems with moving the integrations from YAML to the .storage thing.. :(

**Comment by jcallaghan** [comment]
Happened again today - just Zigbee though. Woke to find my Zigbee devices were unavailable.

The deCONZ web app was still available but not able to communicate with devices. The gateway was also showing no firmware which is a sign it isn't able to access/communicate with the Conbee II stick. Removing the Conbee II from my Synology NAS and reconnecting it fixed this.

**Comment by jcallaghan** [comment]
Sadly another drop today. Notice how the firmware is not available. Removing the Conbee II stick and adding it again makes it available again.

## Before
![image](https://user-images.githubusercontent.com/7449908/85229431-7af34c00-b3e1-11ea-8492-9aa716d13f34.png)

## After
![image](https://user-images.githubusercontent.com/7449908/85229448-9f4f2880-b3e1-11ea-8329-64cd84d2fe7e.png)

**Comment by jcallaghan** [comment]
I moved to ZHA. I've not had any issues since moving to ZHA but I suspect just by writing this I will now be cursed until the end of time with issues in ZHA 😂
