### ISSUE TITLE
Bath water level sensor

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#16]
For many years I've tried to find a solution to prevent a running bath from overflowing. It started in my first house that had an incredibly slow filling bath and often I'd forget it was running. This isn't so bad when the bath overflow can manage to drain the water away but in this particular case it could and on two occasions at least the bath caused a flood. This was at a time when I was getting started with Raspberry Pis and I decided to build out a bathwater level monitoring solution, needless to say, the thing looked bat-crazy in a Tupperware container. It wasn't really a long term solution and I don't recall it being particularly reliable, but the quest was on. 

Move forward a few years and I had got into Home Automation space in a big way. I now had my second or third variant of a Z-Wave gateway and these gave me access to a new type of low powered sensors including water sensors. There was one particular Z-Wave water sensor that I brought to try out (V2). I took inspiration from the bathroom environment at the time to give me some ideas around how I could hold the sensor in the bath and the first solution involved some of my daughter's hair clips to hang it from the overflow waste pipe. This was okay however the sensor had some water ingress over time and wasn't really designed to be submerged. 

My research continued and I came across that same sensor but this time with a wall dock that also included an alarm. This ticked the box for me as it had the audible alarm and the sensor was docked out of the harm of the water and the sensor was attached to a cable allowing it to be placed in the water. Continuing on the theme of using my surroundings for inspiration I decided to use a suction cup after seeing something stuck to the wall with one. I found some bathroom suction cups online that included a bolt which I felt I could hack around with. I was able to pull the bolt out and had a good surface to superglue the suction cup onto the sensor prong. V3 of the solution was great except one thing...reliability. The majority if not all of my Home Automation increasingly sat on the Zigbee protocol (100% of my sensors are Zigbee now) and not Z-Wave so I had a terrible mesh network and the water sensor would undoubtedly never report when used.

The winning solution was in front of me. My Zigbee network. I was keeping a Z-Wave network up for this one sensor. I had recently come across the Aqara range of Zigbee sensors and it dawned on me that I could use one of their water sensors with the same suction cup technique that I used on the Z-Wave sensor. The suction cup glues perfectly onto the battery cover of the water sensor not impeding access to the battery and provides me with the benefit that I can position this sensor at the preferred level for the water in the bath. Version 4 of my bath water level sensor was born! 

## Features
* Zigbee based sensor.
* Inexpensive compared to Z-Wave sensors. 
* Can be positioned at the desired water level.
* Alert integration to persistently alert that the water level has been reached including Text-to-speech (TTS) notifications.

**Comment by jcallaghan** [comment]
#HomeAssistant ```alert``` integration documentation - https://www.home-assistant.io/integrations/alert/

**Comment by jcallaghan** [comment]
## Z-Wave water sensor and hair clips (V2)
https://twitter.com/jamescallaghan/status/1176493950577926144

**Comment by jcallaghan** [comment]
## Z-Wave water sensor and hair clips (V2)
https://twitter.com/jamescallaghan/status/1176493950577926144

<blockquote><img src="https://pbs.twimg.com/ext_tw_video_thumb/1176493883322195969/pu/img/ESEBtTw95y1DW2kr.jpg" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/jamescallaghan/status/1176493950577926144">James Callaghan #Microsoft on Twitter</a></strong></div><div>“My bath is slow to fill and I often forget it’s running. In order to prevent this and avoid wasting water I hacked this together. When the bath is close to full it reminds me through @Sonos. Going to make a better fitting on a 3D printer. #SmartHome https://t.co/gTNlsS4iYi”</div></blockquote>

**Comment by jcallaghan** [comment]
## History - Z-Wave water sensor via probe and suction cup (V3)

**Comment by jcallaghan** [comment]
# ~History~ Zigbee Bath Water Level Sensor (V4)

![image](https://user-images.githubusercontent.com/7449908/89280689-e109fa80-d640-11ea-9ab5-2807317a6a86.png)

https://twitter.com/jamescallaghan/status/1228050172367822853

**Comment by jcallaghan** [comment]
https://www.amazon.co.uk/gp/product/B005G2BY2K/

**Comment by oh-sebastian-birlet** [comment]
Silly quesiton, but in the past I recall a normal plug fitted with a float. The length of chain between float and plug would then unplug the plug. I came across your GH while looking for solution to detect if there was water in the bath.  But found this: The [DFRobot SEN0715](https://www.dfrobot.com/product-3114.html?utm_source=chatgpt.com) looks particularly suitable as can detect water through 6mm of acrylic. Also alternative would be ultrasonic sensor directly above bath detecting how far to the opposite surface. Just thought might be useful to you.
