### ISSUE TITLE
Move from deCONZ over to ZHA

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#167]
deCONZ has been absolutely rock solid for the last year but recently I've had two occasions where I've lost connectivity with my Zigbee network and one of these I had to rebuild the integration with Home Assistant (#109). While I appreciate it's reliability up until this point I'm not so forgiving over the two issues and plan to move to [Zigbee Home Automation (ZHA)](https://www.home-assistant.io/integrations/zha) which leverages [Zigpy](https://github.com/zigpy/zigpy).

I will need support for:
* [x] Hue lights, remotes and sensors
* [x] Aqara sensors
* [x] Smartthings sensors and plugs

## Questions:
* Is there a way to migrate? No.
* Is there the equivalent to the network map that was available via deCONZ? Yes, [ZHA map](https://github.com/zha-ng/zha-map)

## References
* [ZHA device handlers](https://github.com/zigpy/zha-device-handlers)
* [ZHA map](https://github.com/zha-ng/zha-map)
* [ZHA network visualization card](https://github.com/dmulcahey/zha-network-visualization-card)
* [ZHA network card](https://github.com/dmulcahey/zha-network-card)

## Zigbee network
This is my Zigbee network minus some devices I have paired since the last issue. I have just over 150 Zigbee devices.

![image](https://user-images.githubusercontent.com/7449908/85202159-52455680-b2fc-11ea-973c-a93f13ed758b.png)

## deCONZ
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2875
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2863

**Comment by jcallaghan** [comment]
# Approach to joining devices

**Comment by jcallaghan** [comment]
# Pairing tools of choice
* Park tools pick - particularly helpful for Smartthings multi-sensor. The 90° bend on the pick makes it much easier to reach the pairing button on door and window sensors.
* Phone sim remover tool - great for Hue but I didn't need to pair any Hue sensors.
* Listen to ```zha_event``` events in Developer Tools > Events.

[[picture]]

**Comment by jcallaghan** [comment]
# Device codes
Device| Code| Battery | Join |
-----|--------|---------|------|
Hue indoor motion sensor | SML001 | | |
Hue outdoor motion sensor | SML002 | | |
Hue 4 button remote  | | | |
[Aqara Temperature Sensor](https://www.aqara.com/us/temperature_humidity_sensor.html) | LUMI lumi.weather| CR2032 | Hold pairing button for 5 seconds |
Aqara door LUMI | lumi.sensor_magnet.aq2 | | | 
Aqara button v1 | | | |
Aqara button v2 | | | |
[Aqara water](https://www.aqara.com/us/water_leak_sensor.html) | | | |
Aqara motion | | | |
Aqara cube | | | |
Smartthings button Samjin  | | | button 10 seconds
Smartthings door  | | | 10 seconds

**Comment by jcallaghan** [comment]
# Groups
* You must have two lights in order for a light group to be created. deCONZ worked with just one light. I built scenes and automations around using light groups rather than single lights. This is a little frustrating as this means I would have light groups created in ZHA and YAML for light groups with just one light. Instead, I removed all my ZHA light groups and created them all in YAML. The reason I use light groups is it is cleaner to reference the light group in automation regardless of the lights in the light group. Overtime if I add or remove lights from a room I don't need to change anything other then the mapping in the light group.
* On some sensors, I have noticed the voltage is included as an attribute along with what type of battery is used. This is great and something I can add to my battery automation. #120 
* When you do create a group an entity like ```light.dining_room_zha_group_0x0002``` is created (see image below).
* There is no friendly name property available for light groups via YAML. I'll need to see if I can change these via customise.

![image](https://user-images.githubusercontent.com/7449908/85333972-6cd12880-b4d2-11ea-87da-e4af7238066c.png)

**Comment by jcallaghan** [comment]
# 🚨 Smartthings sensors unavailable 
My Smartthings sensors have become unavailable after restarting Home Assistant. Aqara and Hue devices seem fine. It seems those with the ```unk_manufacturer```manufacturer ID are those that become unavailable. After looking at the device information nothing was know about these devices.

![image](https://user-images.githubusercontent.com/7449908/85300957-231b1a80-b49f-11ea-9804-31e8ac54ba14.png)

I noticed when I tried pairing one again the device LED wasn't very bright. After changing out the battery the light was much brighter and it joined with the correct device information. I don't think this is related to the battery more that these devices have lost connection.

Before...

![image](https://user-images.githubusercontent.com/7449908/85303075-f0beec80-b4a1-11ea-94da-b485a6933246.png)

After...

![image](https://user-images.githubusercontent.com/7449908/85303424-5d39eb80-b4a2-11ea-86be-9c436700cd57.png)

**Comment by jcallaghan** [comment]
# 🚨 No hold or double press events for Hue remotes

**Comment by dmulcahey** [comment]
> # 🚨 Smartthings sensors unavailable
> My Smartthings sensors have become unavailable after restarting Home Assistant. Aqara and Hue devices seem fine. It seems those with the `unk_manufacturer`manufacturer ID are those that become unavailable. After looking at the device information nothing was know about these devices.
> 
> ![image](https://user-images.githubusercontent.com/7449908/85300957-231b1a80-b49f-11ea-9804-31e8ac54ba14.png)
> 
> I noticed when I tried pairing one again the device LED wasn't very bright. After changing out the battery the light was much brighter and it joined with the correct device information. I don't think this is related to the battery more that these devices have lost connection.
> 
> Before...
> 
> ![image](https://user-images.githubusercontent.com/7449908/85303075-f0beec80-b4a1-11ea-94da-b485a6933246.png)
> 
> After...
> 
> ![image](https://user-images.githubusercontent.com/7449908/85303424-5d39eb80-b4a2-11ea-86be-9c436700cd57.png)

@Adminiuga this is something we should look in to. The "unknown" manufacturer / model stuff still seems to be an intermittent issue.

**Comment by jcallaghan** [comment]
# 🚨 Aqara Vibration Sensor
The angle, xyz post and strength attributes were previously available as attributes to the entity when using deCONZ. These don't appear to be available in ZHA which will render some automations which leverage these attributes broken such as #96.

**Comment by dmulcahey** [comment]
> # 🚨 Aqara Vibration Sensor
> The angle, xyz post and strength attributes were previously available as attributes to the entity when using deCONZ. These don't appear to be available in ZHA which will render some automations which leverage these attributes broken such as #96.

We publish the tilt information as events. Can you explain what you mean a bit more by strength? We can explore supporting the same functionality. I have several of these so getting them working similarly shouldn’t be tough.

**Comment by jcallaghan** [comment]
# Conbee II stick unavailable - timeline and notes

1. I lost power to the house and backup power which resulted in total power-out.
1. Home Assistant reported issues accessing the Conbee II device and I had no control of my Zigbee devices.
1. When my Synology NAS came back up it appears the deCONZ docker container started. I had only turned it off and not disabled it from auto-starting while I started to test out ZHA.
1. The Conbee II device is visible on the NAS. It can be seen with lsusb and has the same device path. 
1. Turned off deCONZ and disabled auto-restart in Docker.
1. Restarted Home Assistant Docker container several times and it still would not see the Conbee II device.
1. Restarted the Docker service on my Synology NAS. Issue persisted.
1. Turned off Home Assistant and ran the deCONZ container. The device was available and reported the firmware correctly. I reloaded the last known network config through the [hidden network menu.](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_59).
1. Turned off deCONZ and brought Home Assistant back up. Issue persisted.
1. Cleared the Home Assistant container and pulled down the image again. Conbee II device available again.
1. Devices are available and show as such in Home Assistant but they cannot be controlled. Possible devices still reconnecting.

**Comment by Adminiuga** [comment]
hard to say without knowing the previous good network configuration and comparing the new one. I think the backup of the configuration is done by the phoscon, and depending on how long you've been running ZHA, the network config may have changed since the last backup. 
Do you get attribute report from the devices?

**Comment by adonno** [comment]
Oh man wat an adventure.

**Comment by jcallaghan** [comment]
# ZHA add device page
Few times I have been on the add device page and performed a number of scans. This results in the log text area becoming quite heavy and after a period the page becomes slow and eventually, the browser (Edge) suggest to kill the tab.

**Comment by Adminiuga** [comment]
how many scans have you performed? Usually the intention was to join one or a couple of devices and then go back.
But with 150 devices on the network, yeah, you are going to get a lot of noise from the other devices. 
Unless you need the realtime feedback when joining devices, you could also call `zha.permit` service and join devices, that would work in the background, without any realtime logging in the web ui

**Comment by jcallaghan** [comment]
> how many scans have you performed? Usually the intention was to join one or a couple of devices and then go back.
> But with 150 devices on the network, yeah, you are going to get a lot of noise from the other devices.
> Unless you need the realtime feedback when joining devices, you could also call `zha.permit` service and join devices, that would work in the background, without any realtime logging in the web ui

Thanks for the pointers on the ```zha.permit``` service. You've described exactly what I've done where I join a few devices loop back and join some more. I've had a handful of devices that have refused to join which is where I've experienced this hanging issue. This is most likely from repeated join attempts while also receiving tons of noise.

**Comment by jcallaghan** [comment]
# Two oddities

1. One of my Smartthings Sensors has come through as "on/off" as opposed to "open/closed". Curious how the device class is determined and is this something I can fix or is it a device remove/join again?
![image](https://user-images.githubusercontent.com/7449908/85751095-2e21b500-b702-11ea-99f4-e9a44f3147f7.png)

1. One of my Aqara temperature sensors has come through with no battery level entity. Suspect this is due to the missing quirk.
![image](https://user-images.githubusercontent.com/7449908/85757623-8c9d6200-b707-11ea-89d6-9b9499faec56.png)

**Comment by Adminiuga** [comment]
For aqara battery a quirk is required. Either it wasn't discovered completely or it is a different model and does not match the current signature. 
Post Zigbee information for it.

**Comment by jcallaghan** [comment]
@Adminiuga Aqara temperature sensor with missing battery information.
```
{
  "node_descriptor": "<Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0302",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0402",
        "0x0403",
        "0x0405",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0004",
        "0xffff"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.weather",
  "class": "zigpy.device.Device"
}
```

**Comment by jcallaghan** [comment]
Smartthings reporting normally
```
{
  "node_descriptor": "<Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4673 maximum_buffer_size=82 maximum_incoming_transfer_size=82 server_mask=11264 maximum_outgoing_transfer_size=82 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x0402",
        "0x0500",
        "0x0b05",
        "0xfc02"
      ],
      "out_clusters": [
        "0x0003",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Samjin",
  "model": "multi",
  "class": "zhaquirks.samjin.multi2.SmartthingsMultiPurposeSensor2019"
}
```

and Smartthings reporting with the wrong device class.

```
{
  "node_descriptor": "<Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4673 maximum_buffer_size=82 maximum_incoming_transfer_size=82 server_mask=11264 maximum_outgoing_transfer_size=82 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x0402",
        "0x0500",
        "0x0b05",
        "0xfc02"
      ],
      "out_clusters": [
        "0x0003",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Samjin",
  "model": "multi",
  "class": "zhaquirks.samjin.multi2.SmartthingsMultiPurposeSensor2019"
}
```

I also have this global customisation in play.

``` 
"binary_sensor.*_window*contact":
  icon: mdi:window-open-variant
```

**Comment by dmulcahey** [comment]
> # Hanging ZHA add device page
> Few times I have been on the add device page and performed a number of scans. This results in the log text area becoming quite heavy and after a period the page becomes slow and eventually, the browser (Edge) suggest to kill the tab.

The new version of this page has the log hidden by default. I haven't peeked too much at what Bram did but I am sure it will be way more responsive. Definitely something we can look at in more detail to see what can be done to make this better.

**Comment by Adminiuga** [comment]
Your aqara has a different device type. Must be a different revision. Needs a new quirk to match signature.

For smartthings sensor, read the `zone_type` attribute of the IASZone cluster on both devices and compare the results. That value control the device class, but I don't remember if smartthings gives out the correct information or not. And since you are using templating, make sure your entity_id matches.

**Comment by dmulcahey** [comment]
> Your aqara has a different device type. Must be a different revision. Needs a new quirk to match signature.
> 
> For smartthings sensor, read the `zone_type` attribute of the IASZone cluster on both devices and compare the results. That value control the device class, but I don't remember if smartthings gives out the correct information or not. And since you are using templating, make sure your entity_id matches.

I had him do that :) Great minds... lol Waiting for the results after a restart of HA.

**Comment by jcallaghan** [comment]
@dmulcahey ps the log is super useful still. AS busy as it is for me when pairing devices I was able to see device handles flashing through which was a good clue it had discovered the device I was pairing.

And as throughout this process @dmulcahey @Adminiuga I really appreciate your support. This has provided me with a ton of reassurance that this was the right thing to do. No regrets whatsoever. Thank you 🙏

**Comment by jcallaghan** [comment]
Further [share on Twitter](https://twitter.com/jamescallaghan/status/1276591530799742977).

**Comment by jcallaghan** [comment]
# [Tim Messerschmidt @SeraAndroid](https://twitter.com/SeraAndroid/status/1276594353977335809)
>What's** the experience like in comparison to deconz? How long does it take for the network to be ready after a restart?

Having ZHA within Home Assistant is great...just the one place to manage things is always a benefit. And one less Docker image! I've noticed an improvement in the latency with light on/off events for sure.

I thought at first it would cause problems with the amount of time I bounce Home Assistant due to dev work but ZHA is up in no time at all and it has fixed a few devices I've had issues with. I'd say ZHA is up before Home Assistant has finished loading all the components. 

I'm working with @dmulcahey to see if we can create a ZHA ready like an event but from our conversation, it is already up before Home Assistant is started. I'd love an event that I can use to report if there are issues.

**Comment by jcallaghan** [comment]
[Martin Pugh @thepugmiester](https://twitter.com/thepugmiester/status/1276594767468662784)
> I'm just on the verge of starting the ZigBee rollercoaster. I have a Conbee 2 and a stack of IKEA lights and remotes already taking to ha using the ones hub. I've just got deCONZ running  but as I'm starting from scratch anyway, world you recommended going the LHA route?

Rollercoaster...Dreamliner! A great choice for your gateway and lights are key for a stronger mesh. I have 56 lights and when I moved this over from my Hue bridge my Zigbee game changes massively! Knowing what I know now, I wish I started off with ZHA 8 months ago. ⭐⭐⭐⭐⭐

There are still some kinks to work out but you only need to see the positive engagement I've already received to see ZHA is a serious contender.

**Comment by adonno** [comment]
I've Tried adding a Xiaomi Mi Open Close but I'm only getting 
![image](https://user-images.githubusercontent.com/13216947/85958704-a9e85f80-b997-11ea-9e07-4d0de7986e36.png)

**Comment by dmulcahey** [comment]
It didn’t pair correctly. Remove it via the UI. Press the button on the device while doing this. Wait a minute and rejoin it. Once it starts to pair you need to press the button on it every couple seconds until it’s paired.

**Comment by adonno** [comment]
@dmulcahey how can I remove it via the UI I have no button for this specific device on the ui

**Comment by Adminiuga** [comment]
@adonno which version? If on 0.111, do you have device in config panel -> zha -> device drop down? I assumed the screen shot was from there

**Comment by adonno** [comment]
![image](https://user-images.githubusercontent.com/13216947/86001415-22d6ce00-ba0f-11ea-9919-9fc352b30118.png)

Home Assistant 0.112.0b2 supervised on ubuntu

**Comment by dmulcahey** [comment]
@adonno you’re in the OOTB device screen... go to configuration-> Zigbee Home Automation

**Comment by adonno** [comment]
maybe I'm doing something wrong but ZHA has moved

![zigbee](https://user-images.githubusercontent.com/13216947/86008029-8dd8d280-ba18-11ea-971f-a2ec0a699481.gif)

**Comment by dmulcahey** [comment]
@adonno whoops, missed that you were on the beta! In the beta it’s exactly where you are. I have no idea why the buttons aren’t there though. Try just resetting the device and re-pairing it again with the instructions from above without removing it.

**Comment by adonno** [comment]
Thanks it worked. I noticed that i wasn’t able to add devices via a „repeater“ 
There is a button „add via this device“ but it seemed impossible. Only way was to move in reach to the stick.

**Comment by jcallaghan** [comment]
# Device codes
See my Wiki ZHA Devices page https://github.com/jcallaghan/home-assistant-config/wiki/ZHA-Devices

**Comment by jcallaghan** [comment]
I think my move and journey to ZHA is firmly over. I have a handful of dev devices still in a box that I won't join now until I need them. Thanks again to @dmulcahey and @Adminiuga for their amazing support during this process. Your hard work and dedication to the project and the wider Home Assistant community are much appreciated, thank you!

![image](https://user-images.githubusercontent.com/7449908/88906786-c35b2080-d24f-11ea-8a27-d1f16cd63ab6.png)

**Comment by basnijholt** [comment]
Thanks a lot for documenting this publicly! It's quite helpful.

**Comment by donnib** [comment]
@jcallaghan what kind of routers do you use ? I have about 70 devices where most of them were GU10 Ikea Trådfri and had so many issues with them locking up and requiring power cycle so i have started switching to Hue GU10 and seems much more stable (have not had a Hue GU10 requiring power cycle yet and it's more than a week that i did the change). I use deConz and RaspBee but i would really like to move to ZHA to get rid of the deConz not becaus i don't like it but i have to maintain the rPI and i am afraid of SD card issues. At the moment i am testing with Sonoff Zigbee bridge and ZHA. You are using Conbee ?

**Comment by basnijholt** [comment]
BTW, I moved all my 50+ devices over to ZHA from deCONZ two weeks ago and was really happy with the improved event handling in automations. Unfortunately, ZHA proved to be extremely unreliable for me (see https://github.com/zigpy/zigpy-deconz/issues/140) and therefore I moved everything back to deCONZ this weekend. Apparently, having **only**  Hue lights that can act as routers isn't optimal for ZHA. There are many others that do not experience these problems, I just want to leave a warning somewhere ;)

**Comment by donnib** [comment]
@basnijholt thx, i currently have 17 GU10 Hue but i do have few other routers such as IKEA tradfri but i want to get rid of them.

**Comment by MrMoosieMan** [comment]
> BTW, I moved all my 50+ devices over to ZHA from deCONZ two weeks ago and was really happy with the improved event handling in automations. Unfortunately, ZHA proved to be extremely unreliable for me (see [zigpy/zigpy-deconz#140](https://github.com/zigpy/zigpy-deconz/issues/140)) and therefore I moved everything back to deCONZ this weekend. Apparently, having **only** Hue lights that can act as routers isn't optimal for ZHA. There are many others that do not experience these problems, I just want to leave a warning somewhere ;)

Well, darn.  I'm in the middle of figuring out which technology to go with and your review is having me second guess my approach.  I have about 50 Hue lights and was thinking I would use ZHA - maybe this is not a good idea.  Thanks!

**Comment by jcallaghan** [comment]
> > BTW, I moved all my 50+ devices over to ZHA from deCONZ two weeks ago and was really happy with the improved event handling in automations. Unfortunately, ZHA proved to be extremely unreliable for me (see [zigpy/zigpy-deconz#140](https://github.com/zigpy/zigpy-deconz/issues/140)) and therefore I moved everything back to deCONZ this weekend. Apparently, having **only** Hue lights that can act as routers isn't optimal for ZHA. There are many others that do not experience these problems, I just want to leave a warning somewhere ;)
> 
> Well, darn. I'm in the middle of figuring out which technology to go with and your review is having me second guess my approach. I have about 50 Hue lights and was thinking I would use ZHA - maybe this is not a good idea. Thanks!

It certainly is the right idea. I would not go back - both Home Assistant and ZHA have continued to grow and while I might have had some troubles migrating I've not looked back! ZHA is absolutely rock solid and hasn't given me any trouble in a long time. I now have circa 180 devices connected to ZHA - mostly Hue bulbs, motion sensors, and remotes along with Smartthings plugs and contact sensors and a ton of Aqara sensors (water, contact, temperature).
