### ISSUE TITLE
Home Assistant start time and time running sensor ⏱📈🚦

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#178]
A few times I've wondered how long Home Assistant has been running or if I'm testing something when it last started (my memory sucks and I forget if I've restarted it or not).

My plan is to trigger an automation when Home Assistant starts. This will send me a notification and update an ```input_datetime``` sensor. And just for fun, I'll create a template sensor to calculating the uptime (days:hours:minutes).

**Comment by adonno** [comment]
I will ’borrow‘ that idea

**Comment by jcallaghan** [comment]
# Templating fun
While [relative_time](https://www.home-assistant.io/docs/configuration/templating/#time) filter exists, it only displays the highest value i.e. 2 days. I wanted to know my uptime in days, hours and minutes.

```yaml
Date time: {{ states('sensor.date_time') }}
Home Assistant started: {{ states('input_datetime.home_assistant_started') }}

Date time timestamp: {{ as_timestamp(now()) }}
Started timestamp: {{ as_timestamp(states('input_datetime.home_assistant_started')) }}

{% set totalminutes = (as_timestamp(now()) - 
as_timestamp(states('input_datetime.home_assistant_started'))) / 60 %}

{% set hours = (totalminutes / 60) | round(0,'floor') %}
{% set minutes = (totalminutes % 60) | round(0,'floor') %}
{% set days = (hours / 24) | round(0,'floor') %}
{% set weeks = (days / 7) | round(0,'floor') %}

Total Minutes: {{ totalminutes }}
Weeks: {{ weeks }}
Days: {{ days }}
Hours: {{ hours }}
Minutes: {{ minutes }}

{% if totalminutes <= 59 %}
00:00:{% if minutes <= 9 %}0{{ minutes }}{% else %}{{ minutes }}{% endif %}
{% elif totalminutes >= 60 and totalminutes <= 1400 %}
00:{% if hours <= 9 %}0{{ hours }}{% else %}{{ hours }}{% endif %}:{% if minutes <= 9 %}0{{ minutes }}{% else %}{{ minutes }}{% endif %}
{% elif totalminutes >= 1401 and totalminutes <= 9800 %}
{% if days <= 9 %}0{{ days }}{% else %}{{ days }}{% endif %}:{{ hours - (days * 24) | round(0,'floor') }}:{% if minutes <= 9 %}0{{ minutes }}{% else %}{{ minutes }}{% endif %}
{% endif %}
```
![image](https://user-images.githubusercontent.com/7449908/85396938-8e6df680-b54a-11ea-8fe0-d84f0beccea1.png)

**Comment by jcallaghan** [comment]
Relates to #179.

**Comment by jcallaghan** [comment]
# Friendly attribute
To replicate ```relative_time``` filter I've created a friendly attribute that displays the uptime in a more readable way. I can then use this attribute in alerts. I think this would be great for @CCOSTAN 's briefing and Tweets. 

Just minutes...
![image](https://user-images.githubusercontent.com/7449908/85406717-16a7c800-b55a-11ea-95bf-191c07537e96.png)

Hours and minutes...
![image](https://user-images.githubusercontent.com/7449908/85406744-24f5e400-b55a-11ea-90d3-212f59593bc9.png)

Days, hours and minutes...
![image](https://user-images.githubusercontent.com/7449908/85406861-52db2880-b55a-11ea-9521-460dbc373d9f.png)

**Comment by jcallaghan** [comment]
# HTML5 notification example
Raw sensor value (DD:HH:MM)

![image](https://user-images.githubusercontent.com/7449908/85406224-64700080-b559-11ea-9a89-bcdd3710e9ea.png)

Or with the lastest commit which uses the friendly attribute that I've added to the uptime sensor.

![image](https://user-images.githubusercontent.com/7449908/85407771-89fe0980-b55b-11ea-9e08-dfb90c85b3f0.png)

**Comment by jcallaghan** [comment]
# Restart time idea
I guess I could also add another date time to track the restart time when the restart is fired. Then on start calculate the time difference to work out restart time. I don't need this right now but it would be a helpful statistic to track. I know this is something that is reported in the logs if I ever need it.

**Comment by jcallaghan** [comment]
[Shared on Twitter](https://twitter.com/jamescallaghan/status/1275419247150325760).

![image](https://user-images.githubusercontent.com/7449908/85422089-17962500-b56d-11ea-9147-6720c5b785da.png)

* Note [Frencks reply](https://twitter.com/Frenck/status/1275435871487971329) about the efficiency and rather than using a template sensor just calling the template when the automation runs.

**Comment by CCOSTAN** [comment]
> # Friendly attribute
> To replicate `relative_time` filter I've created a friendly attribute that displays the uptime in a more readable way. I can then use this attribute in alerts. I think this would be great for @CCOSTAN 's briefing and Tweets.
> 

I've actually had this for a while now.. (since 2017) . :) 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/sensor/hass_stats.yaml

It's a different way to do it .. this one uses a command line sensor every 12 minutes. 
Might be worth changing though for efficiency as per Franck.
