### ISSUE TITLE
Smoke alarm batteries changed chore tracker 🔥🔋📅

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#220]
Create two new ```input_datetime``` entities to record when I last changed my Nest smoke alarm batteries. This evening my cast iron pan got the better of me and triggered my Nest smoke alarms. I caught the warning but apparently the smoke was too much and the siren went off. Shortly after silencing the alarms, they both started beeping periodically to indicate their batteries were low.

I'll create an automation to remind me to check the batteries every three months and to change them each year. I think I haven't changed them in two years.

**Comment by jcallaghan** [comment]
#HomeAssistant ```input_datetime``` integration documentation - https://www.home-assistant.io/integrations/input_datetime/

**Comment by adonno** [comment]
I guess them beeping at you isn't enough to remind you to change the battery ? :-)

**Comment by jcallaghan** [comment]
> I guess them beeping at you isn't enough to remind you to change the battery ? :-)

This time around it was fine. But I'd rather not have low batteries in them when I actually need them. Until Nest becomes available there is no harm in a subtle reminder to check them. I've been positioned once before by carbon dioxide and let's just say it wasn't very nice at all. Home Assistant always has my back so what are a couple more basic chores.

**Comment by jcallaghan** [comment]
```input_datetime``` fields created #221, just the notification reminder automation now.

![image](https://user-images.githubusercontent.com/7449908/87256330-63136300-c489-11ea-99a8-27d8062066bb.png)

**Comment by jcallaghan** [comment]
Templating.

```yaml
Date time: {{ as_timestamp(states.sensor.date_time.last_changed) }}
Now: {{ as_timestamp(now()) }}

Chore timestamp attribute: {{ state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') }}
vs state: {{ as_timestamp(states('input_datetime.chore_nest_upstairs_batteries_last_changed')) }}

Seconds in 90 days (3 months): {{ (60*60*24)*90 }}
Seconds in a minute x by minutes in an hour x by hours in a day x by 90 days.

90 days has pasted: {{ as_timestamp(states.sensor.date_time.last_changed) >= (state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') + (60*60*24)*90) }}
180 days has pasted: {{ as_timestamp(states.sensor.date_time.last_changed) >= (state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') + (60*60*24)*180) }}
270 days has pasted: {{ as_timestamp(states.sensor.date_time.last_changed) >= (state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') + (60*60*24)*270) }}
360 days has pasted: {{ as_timestamp(states.sensor.date_time.last_changed) >= (state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') + (60*60*24)*360) }}
450 days has pasted: {{ as_timestamp(states.sensor.date_time.last_changed) >= (state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') + (60*60*24)*450) }}
540 days has pasted: {{ as_timestamp(states.sensor.date_time.last_changed) >= (state_attr('input_datetime.chore_nest_upstairs_batteries_last_changed','timestamp') + (60*60*24)*540) }}
```

```
Date time: 1594594981.055409
Now: 1594594985.088987

Chore timestamp attribute: 1594508400.0
vs state: 1594508400.0

Seconds in 90 days (3 months): 7776000
Seconds in a minute x by minutes in an hour x by hours in a day x by 90 days.

90 days has pasted: False
180 days has pasted: False
270 days has pasted: False
360 days has pasted: False
450 days has pasted: False
540 days has pasted: False
```

![image](https://user-images.githubusercontent.com/7449908/87258565-7b40ad80-c49c-11ea-8ae4-efae888123cf.png)

**Comment by jcallaghan** [comment]
#HomeAssistant ```binary_sensor``` integration documentation - https://www.home-assistant.io/integrations/binary_sensor/ and https://www.home-assistant.io/integrations/binary_sensor.template/

**Comment by jcallaghan** [comment]
In the end, I created a template binary_sensor which is 'on' if the time elapsed since the batteries were changed falls into one of the days passed as shown above. This ```binary_sensor``` triggers an automation the reminds me to test/check the smoke alarms.

**Comment by jcallaghan** [comment]
### Persisting alerts
I could create an input_boolean and use an automation to turn this on when the template binary_sensor is turned on. Then these notifications/alerts could persist until the input_boolean is turned off through an actionable alert for example.
