### ISSUE TITLE
Wiki assets

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#54]
You can't paste images into the wiki pages. To improve how quickly I can work on my Wiki I will use this to store images. Later I will move these into the repo.

**Comment by jcallaghan** [comment]
![image](https://user-images.githubusercontent.com/7449908/81469774-d75a2d80-91de-11ea-88f8-9f51a3fe911b.png)

**Comment by adonno** [comment]
Show-off 😂
